sudo: required

git:
  depth: 1

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
    - NAME_TRAVIS_MODULE=oe_my_new_module
  matrix:
    - DRUPAL_VERSION=8.6.x
    - DRUPAL_VERSION=8.5.x-dev
    - DRUPAL_VERSION=8.5.x
    - DRUPAL_VERSION=8.4.x

before_install:
  - mv $PWD ../$NAME_TRAVIS_MODULE
  - cd ../$NAME_TRAVIS_MODULE
  - ./replace-names.sh
  - docker-compose up -d

install:
  - docker-compose exec -u web web composer require drupal/core:$DRUPAL_VERSION

before_script:
  - docker-compose exec -u web web ./vendor/bin/run drupal:site-setup
  - docker-compose exec -u web web ./vendor/bin/run drupal:site-install

script:
  - docker-compose exec -u web web ./vendor/bin/grumphp run
  - docker-compose exec -u web web ./vendor/bin/phpunit
  - docker-compose exec -u web web ./vendor/bin/behat

notifications:
  email: false
